### ISSUE TITLE
Suppressing output in SUNDIALS from non I/O MPI ranks

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Combustion/PelePhysics#121]
I was starting to implement this discussion https://github.com/LLNL/sundials/issues/51 in PeleC, but quickly realized all the SUNDIALS code is here. Would it be possible to do what I suggest in that issue? We are getting 10s of GBs of text output on some not very large scale runs when SUNDIALS encounters problems it would like us to know about.

**Comment by marchdf** [comment]
@jrood-nrel do we still have this issue? I haven't seen GBs of IO in a while...

**Comment by jrood-nrel** [comment]
I haven't seen it.
