### ISSUE TITLE
ndodecane_35 chemical mechanism missing - need the GPU implementation

### ISSUE THREAD

**Issue by marient** [AMReX-Combustion/PelePhysics#147]
The mechanism was not initially included in PelePhyics even though it was used for a PeleLM demonstration. Now that demonstration needs to be repeated on GPUs on summit. I have the mechanism and transport input files.

**Comment by drummerdoc** [comment]
Marco, make a PR to add to the chem.inp, tran.dat and thermo.dat files so that we have them and can run the Fuego scripts.  Be sure that we haven't already done this (check the  dodecane_lu folder to see of the input files you are using are already there).

**Comment by marient** [comment]
Done, thanks.

**Comment by marchdf** [comment]
Looks like this was done. Closing. Please reopen if not.
