### ISSUE TITLE
Compiling bug-FUEGO

### ISSUE THREAD

**Issue by TJzju** [AMReX-Combustion/PelePhysics#15]
Error while trying to generate the LiDryer model for H2 combustion, according to the guide of FUEGO in "README.md"​. Without any changes of the git-cloning code. 

## error reported:
 >> journal(error) -- ~/....../journal/journal/__init__.py:116:<module>
 -- could not import the C++ bindings for journal
 -- control of diagnostics from extension modules is unavailable
Traceback (most recent call last):
    from journal import _journal as journalmodule
ImportError: cannot import name _journal

**Comment by hsitaram** [comment]
Hi Tjzju,

Did you source the setup.sh script?
If not, do "source ${PELE_PHYSICS_HOME}/Support/Fuego/Pythia/setup.sh" and
then try running the script to generate the LiDryer chemistry file.

Thanks,
Hari

**Comment by TJzju** [comment]
Hi Hari, 

Many thanks for your quick reply. I do source the setup.sh file.  We have tried in two different computers, with the same reporting error. Would that be the problem from the setup.sh file, or from the original code?
Thanks.

TJzju

**Comment by drummerdoc** [comment]
Is PELE_PHYSICS_HOME defined correctly?  The problem looks to be that the python functions are unable to find all the dependent code, and the code in the setup.sh or setup.csh files is intended to make the paths to those .py functions available to python.   

A slightly different way to ask: if you are using bash, did you do ". ${PELE_PHYSICS_HOME}/Support/Fuego/Pythia/setup.sh"?  If you are using a C-shell variant (such as tcsh), did you do "source ${PELE_PHYSICS_HOME}/Support/Fuego/Pythia/setup.sh"?  If you mixed that up, the appropriate variables may not be properly "remembered" in your shell and passed correctly to the python functions.

**Comment by TJzju** [comment]
Hi Marc,
Yes, the PELE_PHYSICS_HOME is correctly defined. Bash is used. 
Actually I have run the PeleLM case of FlameInABox, it works well. This suggests that the setup of $PATH should be fine. I just want to generate a new mechanism with FUEGO. And then I try to run the case of LiDryer. I got the error.

**Comment by drummerdoc** [comment]
So, after you do ". ${PELE_PHYSICS_HOME}/Support/Fuego/Pythia/setup.sh", and do "echo $PYTHONPATH" you have a path which includes the folder "${PELE_PHYSICS_HOME}/Support/Fuego/Pythia/Pythia-0.4/packages/journal"?  The definition of that variable and the dynamic library in "${PELE_PHYSICS_HOME}/Support/Fuego/Pythia/Pythia-0.4/lib"  needs to persist in your shell and be available when you run the python function fmc.py

**Comment by drummerdoc** [comment]
No word on this for a while, and the scripts appear to work for me.  closing.
