### ISSUE TITLE
Missing 1D array react for CVODE on GPU

### ISSUE THREAD

**Issue by marchdf** [AMReX-Combustion/PelePhysics#155]
Hi Lucas, it looks like PR #151 removed 1D flattened array from CVODE on GPU. I am talking about this:

```
int react(realtype *rY_in, realtype *rY_src_in,
          realtype *rX_in, realtype *rX_src_in,
          realtype &dt_react, realtype &time,
          int cvode_iE, int Ncells,
          cudaStream_t stream);
```
from [here](https://github.com/AMReX-Combustion/PelePhysics/commit/ad80536aa16bf688aa319aa519435d8eab859ec5#diff-99c88b509702a8bfb9d[…]a7811cb184db39be84ad28L76).

Is there a reason for that? I am asking because several other codes rely on this functionality. Would it be possible to bring back? Thanks!

**Comment by esclapez** [comment]
Hi Marc, I can, it should be pretty straightforward to put that back on. But is there any reason not to switch to the version taking Array4 as function arguments ? It is more efficient.

**Comment by jrood-nrel** [comment]
I think more codes than just PeleC/LM are using that call which is the issue.

**Comment by hsitaram** [comment]
It might be useful to have that version for some unstructured cases. For e.g. with MarcH's particle-based solver. One of my colleagues had coupled PP with openfoam and was using the flattened-array version on CPU of course. But looks like it is missing in CPU also

**Comment by esclapez** [comment]
Okay, I'll put that back in, but I no longer have a working test case for this functionality, so I'll probably ping one of you when the PR is ready.
