### ISSUE TITLE
ERROR- generate new hydrogen mechanism from files in the CHEMKIN-II format

### ISSUE THREAD

**Issue by Toby-Yang** [AMReX-Combustion/PelePhysics#173]
I want to generate a chemistry mechanism from files in the CHEMKIN-II format. The details of the error:
` File ".../PeleC/Submodules/PelePhysics/Support/Fuego/Pythia/pythia-0.4/packages/fuego/fuego/serialization/c/CPickler.py", line 2121, in <lambda>
    for symbol, coefficient in sorted(reagents,key=lambda x:mechanism.species(x[0]).id):
AttributeError: 'NoneType' object has no attribute 'id'`
How to move this bug?

**Comment by Toby-Yang** [comment]
To download the mechanism files in the CHEMKIN-II format:  https://ars.els-cdn.com/content/image/1-s2.0-S0010218019300501-mmc2.zip

**Comment by drummerdoc** [comment]
I'll take a look at it.  Thanks for reporting it.

**Comment by drummerdoc** [comment]
It doesn't like the reaction "OHX=OH+hv".  In this format, all species on the left or right have to be in the species list.  I understand what you're trying to do, but FUEGO sees it as non-standard.  Can you handle that another way?

**Comment by Toby-Yang** [comment]
> 
> 
> It doesn't like the reaction "OHX=OH+hv". In this format, all species on the left or right have to be in the species list. I understand what you're trying to do, but FUEGO sees it as non-standard. Can you handle that another way?

Thanks for you advice. I delete that reaction and the bug is removed.

**Comment by drummerdoc** [comment]
But, were you counting on that energy loss due to radiation?  If so, we'll have to think a bit about how else to replicate that process in your setup.  But, glad that part's fixed.

**Comment by ll-yang** [comment]
> 
> 
> But, were you counting on that energy loss due to radiation? If so, we'll have to think a bit about how else to replicate that process in your setup. But, glad that part's fixed.
Radiation is not important for my case. So the removal of that reaction only cut off one of  paths that  transform OHX into  OH . I think the total energy is still conserved even if I delete more reactions

**Comment by ll-yang** [comment]
> 
> 
> But, were you counting on that energy loss due to radiation? If so, we'll have to think a bit about how else to replicate that process in your setup. But, glad that part's fixed.

Radiation is not important for my case. So the removal of that reaction only cut off one of  paths that  transform OHX into  OH . I think the total energy is still conserved even if I delete more reactions

**Comment by Toby-Yang** [comment]
> 
> 
> But, were you counting on that energy loss due to radiation? If so, we'll have to think a bit about how else to replicate that process in your setup. But, glad that part's fixed.

Radiation is not important for my case. So the removal of that reaction only cut off one of  paths that  transform OHX into  OH . I think the total energy is still conserved even if I delete more reactions
