### ISSUE TITLE
Variable uninitialized in heptane_3sp.cpp

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Combustion/PelePhysics#18]
`Corr` is uninitialized here it seems:
https://github.com/AMReX-Combustion/PelePhysics/blob/209331b09a60f4a29ee5f3c324f4de65a6c18c12/Support/Fuego/Mechanism/Models/heptane_3sp/heptane_3sp.cpp#L2224

Maybe this translates to other models as well.

**Comment by jrood-nrel** [comment]
This happens in a few other models I see as well. For example:
https://github.com/AMReX-Combustion/PelePhysics/blob/53c97ba8704973065290b4455bd0617e4442001d/Support/Fuego/Mechanism/Models/air/air.cpp#L2185

**Comment by drummerdoc** [comment]
Lower priority, but yeah should be trivial to modify the Python to not do that.

**Comment by drummerdoc** [comment]
Actually, to do this cleanly, we'd probably want to remove all arrays dimensioned with 0-length, and loops that won't be traversed...one can go nuts making it all pretty, but it seems like really wasted effort.  I've going to close this PR and if the issues generate real issues, we can push specific changes needed to address them.
