### ISSUE TITLE
Always true if condition in heptane_3sp.cpp

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Combustion/PelePhysics#19]
https://github.com/AMReX-Combustion/PelePhysics/blob/209331b09a60f4a29ee5f3c324f4de65a6c18c12/Support/Fuego/Mechanism/Models/heptane_3sp/heptane_3sp.cpp#L441
Might translate to other models as well.

**Comment by drummerdoc** [comment]
Fixed in cbc738b
