### ISSUE TITLE
Unicode characters in files

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Combustion/PelePhysics#20]
There are unicode characters in `PelePhysics/Support/Fuego/Mechanism/Models/alzeta/alzeta.cpp`, `PelePhysics/Support/Fuego/Mechanism/Models/LiDryer/LiDryer.cpp`, and `PelePhysics/Support/Fuego/Mechanism/Models/Kolla/Kolla.cpp`

**Comment by drummerdoc** [comment]
I believe you, but can you send the output of whatever it was that identified the issue.  I have some ideas how to find and fix those things, but I have no clue how to confirm that all is well. (sorry for delayed response, BTW, all my GitHub mail is going to spam for some reason).

**Comment by jrood-nrel** [comment]
I think this was solved with the recent bigmech PR because it appears the references with the unicode quotations are there any longer. I will verify and close this if they are gone now.

**Comment by jrood-nrel** [comment]
So the latest PelePhysics has removed some of the unicode characters I was seeing before in LiDryer. There are still 2 I can see. One in Kolla and one in alzeta. They are usually unicode quotes it seems (alzeta is too big to link to line 132855). Probably needs to be removed from the Fuego pickler or cantera files it puts in the comments or whatever:
https://github.com/AMReX-Combustion/PelePhysics/blob/53c97ba8704973065290b4455bd0617e4442001d/Support/Fuego/Mechanism/Models/Kolla/Kolla.cpp#L11254

**Comment by drummerdoc** [comment]
I don't know how to reliably identify these things, and so can't confirm that I can fix them.  You apparently do.  Can you remove the offending characters and push the cleaned versions?
