### ISSUE TITLE
CPickler TODOs

### ISSUE THREAD

**Issue by esclapez** [AMReX-Combustion/PelePhysics#204]
- [ ] Use `const` in sparsity functions (and other relevant places)
- [ ] consider formatting output code with `clang-format`

**Comment by esclapez** [comment]
@marchdf we can probably close that right ?

**Comment by marchdf** [comment]
definitely the second check box. Not the first. But I think we can close this in general, knowing that @jrood-nrel  is slowly propagating the linting to pelephysics.

**Comment by esclapez** [comment]
Okay, I'll close it !
