### ISSUE TITLE
CPickler error while trying to generate mechanism files from CHEMKIN

### ISSUE THREAD

**Issue by RSuryaNarayan** [AMReX-Combustion/PelePhysics#248]
Hello, 

I am trying to parse a high-pressure DME mechanism [here](https://ars.els-cdn.com/content/image/1-s2.0-S0010218018302396-mmc2.zip) into Pele and run into this error after doing ```./make_mechanism.sh```. 
```
Traceback (most recent call last):
  File "/home/suryanarayan/Desktop/PelePhysics/Support/Fuego/Pythia/products/bin/fmc.py", line 22, in <module>
    app.main()
  File "/home/suryanarayan/Desktop/PelePhysics/Support/Fuego/Pythia/pythia-0.5/packages/pyre/pyre/applications/Application.py", line 28, in main
    self.execute(*args, **kwds)
  File "/home/suryanarayan/Desktop/PelePhysics/Support/Fuego/Pythia/pythia-0.5/packages/pyre/pyre/applications/Application.py", line 45, in execute
    self.run(*args, **kwds)
  File "/home/suryanarayan/Desktop/PelePhysics/Support/Fuego/Pythia/pythia-0.5/packages/fuego/fuego/fmc/FMC.py", line 59, in run
    lines = fuego.serialization.save(mechanism, output)
  File "/home/suryanarayan/Desktop/PelePhysics/Support/Fuego/Pythia/pythia-0.5/packages/fuego/fuego/serialization/pickle.py", line 33, in save
    return pickler.pickle(mechanism)
  File "/home/suryanarayan/Desktop/PelePhysics/Support/Fuego/Pythia/pythia-0.5/packages/weaver/weaver/mills/Mill.py", line 26, in pickle
    self._renderDocument(document)
  File "/home/suryanarayan/Desktop/PelePhysics/Support/Fuego/Pythia/pythia-0.5/packages/fuego/fuego/serialization/c/CPickler.py", line 302, in _renderDocument
    self._thermo(mechanism)
  File "/home/suryanarayan/Desktop/PelePhysics/Support/Fuego/Pythia/pythia-0.5/packages/fuego/fuego/serialization/c/CPickler.py", line 745, in _thermo
    speciesInfo = self._analyzeThermodynamics(mechanism, 0)
  File "/home/suryanarayan/Desktop/PelePhysics/Support/Fuego/Pythia/pythia-0.5/packages/fuego/fuego/serialization/c/CPickler.py", line 716, in _analyzeThermodynamics
    m1 = models[0]
IndexError: list index out of range
```
The mechanism seems to have a ```#4``` in one of its species which I deleted to get the species read in properly.  Then, I run into this error. Using the latest PelePhysics version. 

Thank you

**Comment by drummerdoc** [comment]
@RSuryaNarayan can you post the mechanism files you tried to use?

@malihass @jrood-nrel Can you look into recent changes that might lead to this?

**Comment by RSuryaNarayan** [comment]
@drummerdoc the original files in the paper can be downloaded [here](https://ars.els-cdn.com/content/image/1-s2.0-S0010218018302396-mmc2.zip). Additionally, the modified files (due to the species error) are attached. 
[HP_DME.zip](https://github.com/AMReX-Combustion/PelePhysics/files/8489893/HP_DME.zip)

Thank you for your quick response.

**Comment by marchdf** [comment]
Quick question @RSuryaNarayan: did this used to work? Trying to figure out if this is a problem that always existed or recently happened. We don't touch cpickler very often. The last meaningful commit to cpickler was Sept 2021.

**Comment by marchdf** [comment]
Also, it looks like it is throwing an error in `CPickler.py", line 716, in _analyzeThermodynamics` but line 716 in the current version of [Cpickler does not have anything on it](https://github.com/AMReX-Combustion/PelePhysics/blob/development/Support/Fuego/Pythia/pythia-0.5/packages/fuego/fuego/serialization/c/CPickler.py#L716). Are you sure you have the right version? Or maybe you made modifications? The closest line I can find is [707](https://github.com/AMReX-Combustion/PelePhysics/blob/development/Support/Fuego/Pythia/pythia-0.5/packages/fuego/fuego/serialization/c/CPickler.py#L707)

**Comment by RSuryaNarayan** [comment]
@marchdf I wanted to test the mechanism given in the supplementary material of this [paper](https://www.sciencedirect.com/science/article/pii/S0010218018302396) and I encounter this error after I extract the mechanism from it and parse it *as is* into PeleC using ```make_mechanism.sh```. Therefore, the error could either be in CPickler or possibly in the mechanism file. 

I tried using cantera's [ck2cti](https://cantera.org/tutorials/ck2cti-tutorial.html#:~:text=python%20%2Dm%20cantera.ck2cti%20%2D%2Dinput%3Dchem.inp%20%2D%2Dthermo%3Dtherm.dat%20%2D%2Dtransport%3Dtran.dat) parser to get a ```.cti``` file and that worked after using the ```--permissive``` flag. So I am guessing the mechanism is more or less correct. Is there a way to parse ```.cti``` directly in Pele hence?

Hope this helps. Thanks a lot.

**Comment by marchdf** [comment]
Great yeah that helps. So this is a new mechanism and it is failing in PelePhysics but seems like it should work because of cantera being ok. Since this is failing in `_analyzeThermodynamics`... I wonder if something is wrong in `therm.dat` ?

**Comment by marchdf** [comment]
Seems like `H` is misssing thermo data:
```
symbol='H', phase='None', composition=[], source='./mechanism.inp':(17, 0)
```

For air, you would have gotten:
```
symbol='O2', phase='g', composition=[('O', 2.0)], thermo=([1000, 5000]: [3.69757819, 0.000613519689, -1.25884199e-07, 1.77528148e-11, -1.13643531e-15, -1233.93018, 3.18916559]), thermo=([300, 1000]: [3.2129364, 0.00112748635, -5.75615047e-07, 1.31387723e-09, -8.76855392e-13, -1005.24902, 6.03473759]), trans=([107.400, 3.458, 0.000, 1.600, 3.800]: [1]), source='./therm.dat':(19, 0)
```

more digging...

**Comment by drummerdoc** [comment]
Also, in the past I have found confusing behavior when the mech files come from Windows, with carriage return/line feed remnants.  Maybe it's just this simple?  I have a script to clean such things up, basically just runs ``tr -d '\015' `` on the file.  It's a long shot, but maybe useful?

**Comment by marchdf** [comment]
I just checked all the whitespace in `therm.dat` on the same hunch... there was definitely a spurious tab here and there but it didn't fix it. I will try your thing too

**Comment by RSuryaNarayan** [comment]
@marchdf yeah, my doubts were also on ```therm.dat```. I do find thermo data for ```H``` in the file 
```
H                 L 6/94H   1    0    0    0G   200.000  6000.000 1000.000     1  
 0.25000000E+01 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00    2
 0.25473660E+05-0.44668285E+00 0.25000000E+01 0.00000000E+00 0.00000000E+00    3
 0.00000000E+00 0.00000000E+00 0.25473660E+05-0.44668285E+00 0.26219035E+05    4
```
not entirely sure here tho if this is what you need!

**Comment by marchdf** [comment]
Yeah I saw it in there as well which is why I thought maybe it was a whitespace parsing thing. @drummerdoc I ran `tr -d '\015' ` on it and it didn't fix it...

**Comment by hsitaram** [comment]
Most often a therm.dat from another chemistry will work. Can you try using
the LuDME's therm.dat. Hopefully it has all the species in this mechanism
as well.

**Comment by RSuryaNarayan** [comment]
@hsitaram LuDME's therm.dat doesn't work either. This other mechanism seems to have many more species than LuDME's.

**Comment by drummerdoc** [comment]
Near as I can tell, the therm dat appears to be empty for some reason.  I suspect that the qss mods have broken the management of thermo data. :(

**Comment by RSuryaNarayan** [comment]
@drummerdoc so does it seem to be a "mechanism-specific" error?

**Comment by marchdf** [comment]
@drummerdoc qss mods from Malik haven't been merged so I doubt that's the problem?

**Comment by drummerdoc** [comment]
@marchdf My bad.  I was exploring with the use of the PelePhysics linked into the PeleC submodules.
@RSuryaNarayan Not sure yet...so many parallel fires at the moment, not making much progress on this yet.

**Comment by marchdf** [comment]
For everyone on this issue, I created a PR (referenced above) that has all the files and modifications I've made so far. @drummerdoc might have additional ones and @malihass had some other ideas. Looks like there are duplicates in `therm.dat`. Let's make sure we use the same files so we aren't duplicating efforts. The branch is `add-hp-dme`.

**Comment by hsitaram** [comment]
I did some digging. I used LuDME's mechanism.inp and HP_DME's therm.dat.
Fuego generation worked, with 2 changes

1) I had to remove O(SING) and O2(SING) species from therm.dat - not sure what is wrong with them
2) There were places where a number was written as 0.XXXe 02 which needs to be 0.XXXe+02, for example this one - 0.1781557e 02

May be along with the things you guys did, it could work.

Thanks,
Hari

**Comment by marchdf** [comment]
@hsitaram thanks for looking at this as well. I fixed the missing `+` stuff in the PR. I also removed the O(SING) and O2(SING) from therm.dat but that didn't help.

**Comment by hsitaram** [comment]
I am finding more things about this mechanism

1) not sure if we can handle PLOG reactions, I dont think we have it in any other mechanism
2) there are some places where troe reactions are written as TROE/ which errs with fuego, apparently it needs space or tab
like TROE        /x    x  x/

fixing these are harder than I thought :(

**Comment by drummerdoc** [comment]
They are using an alternate form here which doesn't appear to be supported by FUEGO - there are a number of such forms (not supported).  Was talking offline to MarcHdF that we may want to consider adopting the Cantera mech reader and think of Fuego as a "backend" code generator.  That would allow us to remove a ton of obscure python stuff in the Pythia folder and dramatically simplify things.  Any takers??

**Comment by hsitaram** [comment]
For what its worth, I got it working after deleting

1) all reactions with O(SING) and O2(SING)
2) all reactions with PLOG
3) fixing TROE slash issue and deleting one TROE reaction

see tar file

[workingmech.tar.gz](https://github.com/AMReX-Combustion/PelePhysics/files/8492385/workingmech.tar.gz)

**Comment by marchdf** [comment]
Well done @hsitaram ! I can get behind number 3. I have no idea what the impact of 1 and 2 are... Agreed with outsourcing the parsing to cantera.

**Comment by hsitaram** [comment]
I will be ok if this working mechanism gave more or less the same ignition delay as the original one.

**Comment by malihass** [comment]
I just realized that Hari beat me to it!
Here is a folder that automatically process the non working mechanism into a working mechanism. Maybe we can include this in the doc or in the code. Run `processMech.sh` then run `make-mechanism.sh`

[workingmech_malik.zip](https://github.com/AMReX-Combustion/PelePhysics/files/8492534/workingmech_malik.zip)



Crucially, the script_thermo that fix the redundancy in the thermo file was removing
 the temperature range (300, 1000, 5000). I had to change it so that it detect it and does not remove it. Attached here.
 
 
[script_thermo.py.zip](https://github.com/AMReX-Combustion/PelePhysics/files/8492536/script_thermo.py.zip)

**Comment by marchdf** [comment]
Ok I think I found another solution. Check out my PR.
The fixes included:
- renaming `O*(SING)` -> `O*SING`, that way we don't lose those reactions, and then catching those in the Cpickler and using `O` weight
- I fixed the pickler so it ignores `PLOG` and throws a warning instead of erroring out. So we keep those reactions, just don't use PLOG
- There's a TROE line that was using commas, removed those commas

Obv the best solution would be to use cantera's stuff

**Comment by RSuryaNarayan** [comment]
Thanks, @marchdf @hsitaram @malihass for the PR! I will switch to this branch and try this mechanism out. Would ignoring the PLOG make a big difference? 
Thanks

**Comment by marchdf** [comment]
@RSuryaNarayan I have no idea. We would have to read the paper and understand why they are there. Alternatively, follow @hsitaram's suggestion and test it out on ignition delay tests and see if it gives the same as the original mech.

**Comment by malihass** [comment]
@RSuryaNarayan : If you want to see how to compute the ignition delay, you can check the branch `malihass/leanReactEval` and look at the folder `Testing/Exec/HRtest`

**Comment by RSuryaNarayan** [comment]
Thanks @malihass @marchdf . Will check it out.

**Comment by RSuryaNarayan** [comment]
Hello, 

Thanks for merging the ```add-hp-dme``` branch into ```development```. However, I tried to compile the mechanism with PMF and run into the following errors: 

1.```Make.package``` seems to be missing in the ```HP_DME``` folder
2. The compilation stops/gets stuck at ```AMReX_buildInfo.cpp```

I resolved (1) using ```Make.package``` in ```LuDME``` as the names of the files are the same and shouldn't make a difference. Clueless about (2). 

Thanks once again

**Comment by jrood-nrel** [comment]
@RSuryaNarayan I fixed the `Make.package` issue. However, I was then able to build PeleC PMF with `HP_DME` without issue. I have a Mac in which I did `make COMP=llvm Chemistry_Model=HP_DME`.

**Comment by RSuryaNarayan** [comment]
Thanks @jrood-nrel I installed a fresh version and shifted to development in pelephysics. Compiling with GNU doesnt move past the build info. Other mechs work.

**Comment by jrood-nrel** [comment]
I can reproduce your behavior with GCC. However, this mechanism is a 7MB source file. Does it complete if you wait a long time for it?

**Comment by RSuryaNarayan** [comment]
@jrood-nrel I also guess it's an issue with the rather large mechanism. I think it should if I wait long enough. Will let you know when it does! Thanks!

**Comment by RSuryaNarayan** [comment]
@jrood-nrel it indeed compiles after a very long time! Closing this for now.

**Comment by jrood-nrel** [comment]
Clang should compile this much faster for you.
