### ISSUE TITLE
TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by czc-zju** [AMReX-Combustion/PelePhysics#271]
To build a new CHEMKIN based model, the TRANFILE_APPEND.txt is generated and inserted into the chemistry input file,  but when I run the script file make-mechanism.sh, TypeError: list indices must be integers, not str.

**Comment by marchdf** [comment]
We need more specifics... what is the chemkin file(s)? where is python reporting the error?

**Comment by malihass** [comment]
Hi, 
thanks for submitting these files. 
It looks like this is an issue with R16: `H2O2(+H2O)<=>OH+OH(+H2O)`
When we compute the third body mixture, if `(+H2O)` was `(+M)` we would just compute the mixture value. Here, we need to read `sc[H2O.id]`. It seems that the `H2O.id` is not correctly obtained. I will submit a PR to fix this. 
I tested it after the code fix and it seems to work. I encourage you to try it once the PR goes through.

Attached are the mechanism.cpp and mechanism.H 
[mechanism.H.txt](https://github.com/AMReX-Combustion/PelePhysics/files/8663046/mechanism.H.txt)
[mechanism.cpp.txt](https://github.com/AMReX-Combustion/PelePhysics/files/8663048/mechanism.cpp.txt)


Let me know if this works and I will close this

**Comment by czc-zju** [comment]
It does work, it's amazing!!!!!!!!
Thanks a million.
That's awesome
How do you know which reaction is causing the problem?

**Comment by malihass** [comment]
No prob. Closing this then.
