### ISSUE TITLE
Unit mismatch for elementary reactions with arbitrary orders of reaction

### ISSUE THREAD

**Issue by jAnirudh** [AMReX-Combustion/PelePhysics#318]
Hi, 

I was looking at some mechanisms which have reactions with arbitrary reaction orders and found that the units of the pre-exponential coefficient in the Arrhenius rate reactions are not the same as those given by Cantera. I added a few print statements (after line 196 in `production.py`) to compare the units given by Cantera with those computed by PelePhysics, and ran a test for the 3 reaction chem-CH4-2step mechanism (all the reactions prescribe arbitrary reaction orders).

The output of the run is in this file: [ceptr_output.txt](https://github.com/AMReX-Combustion/PelePhysics/files/9425718/ceptr_output.txt). The units are significantly off.

The fix may be fairly easy though. Instead of using 
`ctuc = cu.prefactor_units(cc.ureg("kmol/m**3"), 1 - dim)` as in line 196 of `production.py`, we could extract the unit from Cantera as  `ctuc = cc.ureg(str(reaction.rate_coeff_units).split("at")[0][7:-2].replace("^", "**"))`. Of course there may be a simpler (or cleaner way) of doing this without having to do these string operations.

I did try to test the original and the fix for the homogeneous reactor test using CeptrTest, but, somehow, I was not able to get the PelePhysics simulation to work for either case. If I could get some pointers on how to create the homogeneous reactor test with PelePhysics, I'd be happy to attempt a fix for this issue.

Cheers!

**Comment by marchdf** [comment]
Hi, thanks for reporting this potential problem! I did not pay much attention to the arbitrary reaction orders and it is possible I missed something. What kind of issues were you seeing in trying to set up the test?

**Comment by drummerdoc** [comment]
<Pardon the crossed responses from our team...>

Yeah, the full CHEMKIN spec is not supported by the code in PelePhysics that generates mech code.  Sorry about that.  Arbitrary forward and reverse reaction orders is one that isn't.  There are also some of the reaction rate forms (like Landau) that aren't yet supported either.  If nothing else, we should flag these as failures of the interpreter code so that people won't believe all is well when it isn't.

**Comment by malihass** [comment]
Thanks for reporting the issue! I am not sure about the units issue but I can help out with the homogeneous reactor question.

In our testing suite, we do have an homogeneous reactor test case `PelePhysics/Testing/Exec/IgnitionDelay`. This runs 2 consecutive homogeneous reactor calculations to compute an ignition delay. The way to set it up in the `README.md` in that directory. 

Maybe this would be useful as a starting point? If not, I can help you out and adjust the documentation if necessary.

**Comment by jAnirudh** [comment]
Hey @marchdf @drummerdoc  and @malihass thanks for getting back to me. I completely understand the complexity involved, so no worries!

@marchdf I tried to test the fix I mentioned, but was unable to get my homogeneous reactor case to work with the original `PelePhysics/Support/Mechanism/Models/chem-CH4-2step/mechanism.H` ([plots.pdf](https://github.com/AMReX-Combustion/PelePhysics/files/9430338/plots.pdf)). The results show that is there is no ignition, which effectively means I have not understood how to set the case up at all. I'll have a look at what @malihass suggested and try to work things out.

Cheers!

**Comment by malihass** [comment]
Hmm this looks like a different problem now if the original code does not match Cantera. Can you tell me what the initial mixture is (mass fraction of species initially) and what is the initial pressure. Initial temperature seems to be 750K, is that right?

**Comment by jAnirudh** [comment]
These are the initial conditions I used:
`mechanism.TPX = 750.0, 1.4*ct.one_atm, "O2: 0.20153, CH4: 0.040307, N2: 0.75816"`
which is equivalent to 
`mechanism.set_equivalence_ratio(phi=.4, fuel="CH4", oxidizer="O2:21, N2:79")`
Also, `ndt=1000`

**Comment by hsitaram** [comment]
can you try a constant volume reactor. I think pelephysics integration will not recover the constant pressure reactor from cantera. @malihass can correct me.

**Comment by malihass** [comment]
I can reproduce the results (see below) that @jAnirudh sees which suggests that something is not handled right with `chem-CH4-2step` 
![2step](https://user-images.githubusercontent.com/5544573/187051061-00426df2-b767-4e07-b223-00b7cb48a55f.png)

I regenerated the `.cti` files from the `.inp` file and used this with Cantera. So this is truly a difference between how Cantera and PelePhysics are handling these mechs. 

I tried the same test with `drm19` to make sure that nothing else is broken either in my test case or in PelePhysics. I had to increase initial temperature to see an ignition (otherwise same pressure and mass fractions). `drm19` seems to give consistent results with Cantera (see below).

![drm19](https://user-images.githubusercontent.com/5544573/187051097-00398a74-719b-4b62-9dbf-6330a5deadc3.png)

I tried the same test case with an older version of PelePhysics that used Cpickler, and I also see no ignition.

So: 1) This is mechanism specific 2) This is not something that was broken with CEPTR. Likely, this is a FORD-related problem

Looking at #162, it seems like the reaction rates are lower than they should be.
I just hardcoded the reaction rate changes from @whitmanscu and I get something more reasonable with `chem-CH4-2step` (still not great though)
![2step_fixford](https://user-images.githubusercontent.com/5544573/187051748-c19793a7-6da4-4539-a3a4-df7d2a2ca2d5.png)

To make sure we are running the same tests
See this branch: https://github.com/AMReX-Combustion/PelePhysics/tree/malihass/ford_issue

Under `Testing/Exec/Issue318_ch4_2step`, you can do `bash genMech.sh` to regenerate the  `chem-CH4-2step` mechanism, and do `bash exec.sh` to run the HR test and plot the result against Cantera.

**Comment by jAnirudh** [comment]
@malihass are these the reaction rates you've hard-coded? I pulled them out from the mechanism file from #162 

```
// (0):  2.000000 CH4 + 3.000000 O2 => 2.000000 CO + 4.000000 H2O
k_f = 1.0000000000000002e-06 * 154500000000000 * exp(0.5 * tc[0] - 0.50321666580471969 * (39895) * invT);
// (1):  2.000000 CO + O2 => 2.000000 CO2
k_f = 3.1622776601683795e-05 * 199100000000000 * exp(0 * tc[0] - 0.50321666580471969 * (40000) * invT);
// (2):  2.000000 CO2 => 2.000000 CO + O2
k_f = 1 * 250000000 * exp(0 * tc[0] - 0.50321666580471969 * (40000) * invT);
```

I am able to get these same values from ceptr by replacing 
`ctuc = cu.prefactor_units(cc.ureg("kmol/m**3"), 1 - dim)`  in line 196 of `PelePhysics/Support/ceptr/ceptr/production.py` with 
`ctuc = cc.ureg(str(reaction.rate_coeff_units).split("at")[0][7:-2].replace("^", "**"))`

I also verified that the above change does not affect other mechanisms where FORD are not specified.

But I still suspect that something else is off apart from the reaction rates since we aren't getting a quantitative agreement with Cantera. I will post an update if I find something else. Thanks!

**Comment by malihass** [comment]
Yes those are the changes. I agree, something else might be off.
Once we are confident that we have the FORD stuff working we can regenerate all the other mechanisms and make sure nothing else changed before incorporating it in CEPTR.
Thanks for looking into this!

**Comment by jAnirudh** [comment]
@malihass I am unable to reproduce the plot where you hard coded the reaction rates. Somehow I'm getting the same results as with the original mechanism. I'm not sure where I am going wrong. Could you please share the modified mechanism.H file you are using?

**Comment by malihass** [comment]
@jAnirudh , in case you need it, in the `malihass/ford_issue` branch, the mechanism with hardcoded reaction rates is under `Support/Mechanism/Models/chem-CH4-2step_hardcode`

**Comment by jAnirudh** [comment]
Thanks @malihass , I was struggling initially but then realized that I missed regenerating the mechanism through `genMesh.sh`. Once I did that I was able to replicate the results.

**Comment by marchdf** [comment]
@malihass and Mohammad are going to cross-check with chemkin.

**Comment by jAnirudh** [comment]
Hi @marchdf, @malihass just a quick head-up - I think the problem lies in the ceptr jacobian.py module. Unfortunately I haven't been able to dig into this, but I suspect the analytical Jacobian calculations aren't being correctly performed for FORD reactions. A possible test for this thought could be running the ignition delay case without using AJac while incorporating the hard-coded reaction rates from the previous comments (I think a recent commit allows for not using AJacs?)

**Comment by malihass** [comment]
Hi all,
Ok I went to back to this, and regenerated the results of this 0D case. Mohammad also generated the result with chemkin.
It seems that my old script to generate the output file from the cantera sim was dumping the results in a file named differently than the one I used to make the plot. So I suspect that I was not plotting the right temperature profile with cantera!

`PelePhysics base` is the current version of Ceptr
`PelePhysics mod `is with the modifs of #162 that are hard coded. Integration is done with finite difference for the Jacobian.
I also tried the AJ  `PelePhysics Mod AJ` which seems to work as well although I needed to update the reaction rate in the `aJac` fonction as well.

![Figure_1](https://github.com/AMReX-Combustion/PelePhysics/assets/5544573/5f3ec79d-bfb4-4677-bd8f-d0fa8fb5bd36)

So next steps 
- [x] include the modifs of #162 
- [x] make sure it works with the analytical Jacobian
- [x] revert the safeguards against  FORD mechs.

**Comment by jAnirudh** [comment]
Hi @malihass this is awesome! So if I understand correctly, you didn't have to make any changes to the finite difference jacobian evaluation function in mechanism.(?)H right? The reason I ask is because I've already corrected the ceptr/production.py method which writes the reaction rates that you've hard-coded - I'll send a pull request for that module in the next couple of days. All that then remains is correcting the reaction rates used in the ajac method in ceptr/jacobian.py. I can take a stab at that - time permitting - in the coming week.

**Comment by malihass** [comment]
So the finite difference Jacobian is all done by the SUNDIALS module based on `productionRate` 
As long as `productionRate` is correct, the finite difference Jacobian is correct.
However, for the analytical Jacobian (AJ in the plot above) which is generated by Ceptr , we need to fix these reaction rate as well. So when I tweaked the reaction rates in production rate, I needed to tweak the same way in the `aJac` function.
@jAnirudh  Could you please look at the PR #414 and see if it contains the modifs you wanted to add?
