### ISSUE TITLE
Non-Fuego react calls need to have Init removed

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Combustion/PelePhysics#37]
@EnnaDelfen It looks like only the `Fuego` `actual_reactor.F90` was updated to remove the `Init` parameter. I think this needs to happen for the `Null` cases.

In the meantime, I'm trying to understand why Travis CI and my test suite is working without these changes, but the GNU make TG or HIT cases for example don't build due to this. I think it might have to do with some ifdefs or something.

**Comment by jrood-nrel** [comment]
It looks like the GNU make makefiles were screwed up in PeleC that allowed the `react` call to get compiled in when it wasn't necessary. I am making a pull request to fix that, but the `react` routines in `Null` and `Null_air` should still be updated to be consistent.

**Comment by EnnaDelfen** [comment]
Yes you're right, I did not update those folders... I'm on it !

**Comment by jrood-nrel** [comment]
Thanks! No stress. It exposed an issue in PeleC that needed to be fixed.

**Comment by jrood-nrel** [comment]
Fixed in https://github.com/AMReX-Combustion/PelePhysics/commit/9e4b85cdaff8f058f02971a44b217116c6d0f2e5
