### ISSUE TITLE
Creation of a new chemistry model repertory - Conaire mechanism

### ISSUE THREAD

**Issue by bazharz** [AMReX-Combustion/PelePhysics#380]
Hello everyone,

My objective is to simulate a premixed hydrogen flame using the Conaire reduced kinetic mechanism for PeleLMeX. To achieve this, I need to import a 2D temperature field and mass fraction for 9 species included in the conaire.cti file, obtained from Cantera.

However, I am currently facing an issue regarding the creation of a new Conaire chemistry model. I possess conaire.cti, conaire.inp, and conaire.yaml files, but I lack the .H and .cpp formats to complete the directory. Therefore, I am looking for guidance on how to generate these files to have a complete set of files like the others.

**Comment by malihass** [comment]
Hello, 
So the .cpp and .H are automatically generated with the CEPTR module using the .yaml 
If you look at Tutorial 3 (https://amrex-combustion.github.io/PelePhysics/Tutorials.html) this will show you how to generate the .cpp and .H files. 
Let us know if something is not clear, this can also help us improve the docs.

**Comment by malihass** [comment]
@bazharz  Any update?

**Comment by bazharz** [comment]
Sorry for the late reply!
Thank you!
It works well, now i have the mechanism.cpp and mechanism.H and I did a test and It seems to work well!

**Comment by malihass** [comment]
Great! Closing this then
