### ISSUE TITLE
PelePhysics does not allow non-integer stoichiometric coefficients

### ISSUE THREAD

**Issue by whitmanscu** [AMReX-Combustion/PelePhysics#41]
The title pretty much sums up the issue. I would like to use mechanisms that include non-integer coefficients, however coefficients are hard-coded as integers throughout. This is true in both the pickling/unpickling in conversion from Chemkin as well as the routines in PelePhysics and PeleC (and I assume PeleLM) that use the coefficients.

-Sam

**Comment by EnnaDelfen** [comment]
Hi, can you give the new version of PP dev a try on the mechanism you saw issues before and report bugs ? Thanks !

**Comment by whitmanscu** [comment]
Thanks! The conversion runs without any errors. It does look like the .cpp file generated has all nu (coefficient) values typed as integers still even though they are being set to floats in some cases, so they'll probably be implicitly converted at run-time I would think.

**Comment by EnnaDelfen** [comment]
Could you share your mechanism with me ?

**Comment by whitmanscu** [comment]
Here's the (very simple) propane mechanism. Thermo is taken from grimech.

ELEMENTS
C O H N
END
SPECIES
C3H8 O2 H2O N2 CO CO2
END
TRANS ALL
C3H8               2   266.800     4.982     0.000     0.000     1.000
O2                 1   107.400     3.458     0.000     1.600     3.800
H2O                2   572.400     2.605     1.844     0.000     4.000
N2                 1    97.530     3.621     0.000     1.760     4.000
CO                 1    98.100     3.650     0.000     1.950     1.800
CO2                1   244.000     3.763     0.000     2.650     2.100
END
REACTIONS
C3H8+3.5O2=>3CO+4H2O               2.0E12 0 3.3E4
  FORD /C3H8 0.9028/
  FORD /O2 0.6855/
CO+0.5O2<=>CO2                     4.5E10 0 1.2E4
END

**Comment by EnnaDelfen** [comment]
Ok so if you are referring to the "nuv" in CKINIT, yes you will be fine. What I was afraid of is that your mech has specified orders that replace the stoich coeffs (the FORD).... and I can't remember if in dev it'll work :(. If you have a case you can check your results on, that would be very useful, so you can report if you see big discrepancies.

**Comment by whitmanscu** [comment]
I do get an error for type conversion upon attempted compilation:

error: narrowing conversion of '-3.5e+0' from 'double' to 'int' inside { } [-Wnarrowing]
     nuv[0] = {-1,-3.5,3.0,4.0};

**Comment by EnnaDelfen** [comment]
Should work fine now. Note that I am now sure the FORD reacs are not correctly interpreted in Fuego, I'll implement the changes asap.

**Comment by whitmanscu** [comment]
Thanks! Was the FORD issue always there? If so, any details would be appreciated.

**Comment by EnnaDelfen** [comment]
Yes it has always been an issue in Fuego. Basically, those FORD instructions in CHEMKIN format modify the rates of progress of reactions by adapting the orders of each species (you can read page 27 of this manual https://pdfs.semanticscholar.org/fa1e/a61f7bec2645d7aeb914e05912be5056f695.pdf ). Right now those modifications are just ignored with Fuego. So you will end up with a working mechanism, but with off results. These "tricks" to tweak the reaction rates are usually used in small, global (one or 2 steps) mechanisms to recover the correct evolution for a specific point of operation (P,T,Y). Since Fuego is usually used to produce detailed mechanisms, my guess is that accomodating these "FORD" instructions was just not deemed useful enough until now.

**Comment by whitmanscu** [comment]
Ok, thanks! Let me know when the FORD changes are implemented and I'll give the whole thing a test.

**Comment by EnnaDelfen** [comment]
Should be good now

**Comment by whitmanscu** [comment]
Thanks! Managed to do some testing and looks like it's performing appropriately. I'm closing this ticket - I appreciate the quick fix.

**Comment by whitmanscu** [comment]
Hello, I'm wondering if I closed this issue too soon. I'm trying to run the chemistry model I posted earlier with FORD rates and getting segfaults and nan values in some cases shortly after starting reactions. I was looking at issue #23 and wondering if there were further changes that need to be made in order to fully utilize FORD rates. Is this something you can comment on? Thanks!

**Comment by EnnaDelfen** [comment]
To answer this I need for you to be more precise. I need to know which case/code you are running and which integrator you are using. The jac stuff should not be a problem if you are not using it (as I thought was the case). You were correct that the comp_qf_qr stuff was not good on CPU, my mistake, but this has been rectified in dev now. But even without these modifs, you should not be getting segfaults. What are you trying to run and what exactly is the error ? Thanks

**Comment by whitmanscu** [comment]
Yes, I realized that none of the analytical Jacobian routines are actually used, so that should be fine for now. I'm using PeleC with dvode and trying to ignite premixed propane/air inflow behind a bluff body, using an external source or isothermal bluff body boundaries to start ignition. It appears to run fine without AMR but with multiple AMR levels I'm seeing segfaults. Backtraces suggest the error is in the timestep advance and FillPatch routines, although the exact exit point is not consistent. At this point I don't have any reason to think the PelePhysics routines are to blame, although if you have any suggestions I would welcome them.
