### ISSUE TITLE
Documentation for Installing CVODE 

### ISSUE THREAD

**Issue by Arsalancr7** [AMReX-Combustion/PelePhysics#442]
Hi everyone,
I am trying to install CVODE from the description here [https://amrex-combustion.github.io/PelePhysics/GettingStarted.html#install-cvode-and-suitesparse] but I cannot find " get_sundials_v5dev1.sh or get_sundials_v5dev1_CUDA.sh" in the "$PELE_PHYSICS_HOME/ThirdParty". Also, I was trying to install CVODE and Sundials manually but I am not able to compile them after downloading them online.
I would appreciate it if anyone can help me in this regard
Thank you

**Comment by baperry2** [comment]
Sorry, that documentation is very out of date. I plan to fix the documentation soon, but in the meantime here is how you can compile and run the PelePhysics utilities:

1. Clone PelePhysics, AMReX, and Sundials to wherever is convenient for you:
```
mkdir pele && cd pele
git clone https://github.com/AMReX-Combustion/PelePhysics.git
git clone https://github.com/AMReX-Codes/amrex.git
git clone https://github.com/LLNL/sundials.git
```

2. Set some environment variables so the compiler can find AMReX and Sundials:
```
export AMREX_HOME=$(pwd)/amrex
export SUNDIALS_HOME=$(pwd)/sundials
```

3. Compile the software (similar for all the different executables in Exec)
```
cd PelePhysics/Testing/Exec/ReactEval
make TPL && make -j
```

Let's leave this open until the documentation gets updated though.
