### ISSUE TITLE
Error in running PmfData::deallocate() on GPU

### ISSUE THREAD

**Issue by ensonun** [AMReX-Combustion/PelePhysics#454]
I was trying to use the `PmfData` class in my project. When running on GPU, an error occurred during `deallocate()`, saying that `CArena::free: unknown pointer !!!`.

Upon looking into the code, it seems that the error is caused by the fact that `m_data_d` is allocated with `The_Arena()` (line 48: `PMFData.H`) but is freed by `The_Device_Arena()` (line 61: `PMFData.H`). As a workaround, I substituted `The_Device_Arena()` with `The_Arena()`, so that the allocation and deallocation match. I have tested on both CPU and GPU, the issue appeared to be resolved.

I was wondering if this is a valid solution or if the line `The_Device_Arena()->free(m_data_d)` is intentional. I will be happy to contribute a pull request if the proposed solution aligns with the intended design.

Appreciate your insights. Thank you.

**Comment by marchdf** [comment]
This does feel like a true bug. Great job finding it. Please feel free to open a PR with the suggested change.
