### ISSUE TITLE
Temperature values not returned

### ISSUE THREAD

**Issue by ldowen** [AMReX-Combustion/PelePhysics#51]
https://github.com/AMReX-Combustion/PelePhysics/blob/0be85215a9946a129c0e57646174dc751d0e5934/Eos/Fuego/Fuego_EOS.H#L18

In the `eos_EY2T` and `eos_HY2T` functions, I assume they are supposed to be provided the internal energy or enthalpy and the mass fractions and return the temperature. However, the temperature that is passed in is not a reference or pointer. So a new temperature is instantiated and filled with the correct value, then deleted. The cp functions don't have this issue. Although, it seems like passing non-array variables by reference might make it easier to differentiate them but I am not sure if there are other reasons for doing it the current way.

**Comment by drummerdoc** [comment]
ewe, ick!   Yeah, no idea why those are refs instead of copies.  Anne?

**Comment by EnnaDelfen** [comment]
I'm afraid I don't understand what the issue is

**Comment by EnnaDelfen** [comment]
If it's easy to fix go ahead though ! Especially if it's causing an error

**Comment by drummerdoc** [comment]
The routines he points to are supposed to be returning T, but T is passed by value so nothing done to T in those functions have any effects on the T of the calling routine.  I'm worried about where else this might happen

**Comment by ldowen** [comment]
For the Fuego_EOS, it looks like it is only an issue for `eos_EY2T` and `eos_HY2T` I can change that file and make pull request. I think passing it by reference makes more sense than passing it by pointer (like what is done with the `eos_TY2Cp`). Unless there is some GPU reason that it has to be done that way.

**Comment by EnnaDelfen** [comment]
No the only reason for this is my uncompetence. I'll modify this here, but Marc it might indeed be that other such issues are spread out throughout the code ...

**Comment by drummerdoc** [comment]
There's a bunch of things done like that, it looks like, in the sense that scalar whose return value was needed as passed as a pointer (actually as an array of length 1).  Probably should clean all those up...
I'll fix these right now.  Landon, you're working in the `development` branch?

**Comment by ldowen** [comment]
Correct. I am working in the development branch.

**Comment by EnnaDelfen** [comment]
wait, who's on this then ?

**Comment by drummerdoc** [comment]
me.

**Comment by EnnaDelfen** [comment]
cool

**Comment by drummerdoc** [comment]
Landon, can you pull and check that the fixes make sense?

**Comment by ldowen** [comment]
That is exactly what I was thinking but I think there is a slight problem. I think you need to keep the namespace `void EOS::eos_` in the .cpp file when defining the functions.

**Comment by drummerdoc** [comment]
Dang...hold

**Comment by drummerdoc** [comment]
Try again...
sorry about that

**Comment by ldowen** [comment]
Perfect! Thanks!
