### ISSUE TITLE
#include "IndexDefines.H" in Constant/Simple transport models

### ISSUE THREAD

**Issue by mrieth1** [AMReX-Combustion/PelePhysics#62]
There are #include "IndexDefines.H" statements in Transport.H of the Constant and Simple transport models in the current development branch (503aa16). IndexDefines.H is not provided by PeleLM.

**Comment by EnnaDelfen** [comment]
Yes, indeed. Right now, PLM is not made to work with the current cpp implementations of the transport. Those are specifically tailored for PLC. Bottom line is you should not try to use them in PLM right now unless Marc has decided that it is time to start thinking about it, and then we can discuss of how to make it happen !

**Comment by ldowen** [comment]
Can we make the indices inputs into the function call? I think that's how it was before.

**Comment by drummerdoc** [comment]
I was just confirming with Anne that there is no reason not to restore this to its original form, where each component is passed separately, thereby obviating the need for state index information. This will require simultaneous mods to PelePhysics and PeleC, and might as well be done in a way that is compatible with how PeleLM calls it now.  We'll leave this tag open until that is done, but need to coordinate with PeleC folks to synchronize the change.

**Comment by EnnaDelfen** [comment]
I've just created a new branch labelled 'feature_TransportCppUnif' where I attempted to revert the cpp transport versions to a more generic format. It is consistent with what is done in the F90, where we explicitly provide arrays containing Y/rho/T/D/MU etc. instead of just one array containing everything. We should not need the IndexDefines.H anymore. However, we need to clear this with whoever is using this. Martin, feel free to give it a try. Thanks

**Comment by EnnaDelfen** [comment]
@drummerdoc and @mrieth1 can you tell me if you've had time to look into this feature_TransportCppUnif branch ? If not could you give me some feedback within the month ?
Thanks !

**Comment by drummerdoc** [comment]
Comments added to the branch commits...wasn't sure otherwise where I should put them.

Important, there is an assumption of p=1atm -- wrong!

**Comment by marchdf** [comment]
I think all is fixed here. Please reopen if necessary.
