### ISSUE TITLE
Set SUNDIALS version

### ISSUE THREAD

**Issue by awehrfritz** [AMReX-Combustion/PelePhysics#82]
The ThirdParty makefile currently pulls the latest revision in the SUNDIALS master branch: https://github.com/AMReX-Combustion/PelePhysics/blob/ccf3fe304bae2fee6f18fbc8b0607f4eca92e2a2/ThirdParty/GNUmakefile#L107

This kind of makes it difficult to maintain the same version upon rebuilding the third-party libraries. Since sundials tags their releases in git, this could be simply fixed by adding:
```sh
git checkout v5.3.0
```
Or one could make [sundials](https://github.com/LLNL/sundials) and [SuiteSparse](https://github.com/DrTimothyAldenDavis/SuiteSparse) submodules of PelePhysics.

**Comment by awehrfritz** [comment]
Oh, and forgot to mention: The documentation seems to be out of date on this matter as well: https://pelephysics.readthedocs.io/en/latest/GettingStarted.html#install-cvode-and-suitesparse

**Comment by drummerdoc** [comment]
Yes on both accounts.  I was trying to think of a way to pass the versions IDs through and manage a default, but I like your solution better.

Yeah, need to fix the doc...this TPL thing is still experimental though...it just barely hangs together at the moment.

**Comment by marchdf** [comment]
@jrood-nrel I think we are doing this now right? If so, can we close?
